### PR TITLE
Environment

### LINKED ISSUE #3: Basic Environments (Highest Priority)
# Task
ASAP create:
- [x] Straight path
- [x] Square path
- [x] Rectangular path
- [x] Triangular path
- [x] Curved path

### PR DESCRIPTION
**Pull request by wangbard**
This PR accomplishes a three main things:
1. It adds new environments using single-lane roads
2. Update the PROTO file to fix a problem with the Webots supervisor node not being able to access the sensors
3. Remove the wheel_odometry sensor and instead publish wheel_odom from the differential steering node. This was done because using a PROTO file for our robot lost us access to the solids within the robot. We felt like rather than exposing these solids (like we exposed the sensors for 2), we would simply add noise to the incoming control command to model our wheel odometry sensor.

Closes #3

### CODE REVIEW

**Comment by Siliconlad** [comment]
@SmejoTT what's the status of this? I'd like to get it merged ASAP.

**Comment by Siliconlad** [comment]
@SmejoTT as I said in #3, we may need to do #37 first so that we can easily import robots into these new environments.

**Comment by SmejoTT** [comment]
@Siliconlad Is this ready to be merged?

**Comment by Siliconlad** [comment]
I think so. The only thing left to do with this is update the meadows world with the BoundinObject.

It may even be worth removing that for now and adding it later?

**Review by SmejoTT — APPROVED** [review]
Looks good 👍

**Pull request merged**
