### PR TITLE
Robot model

### PR DESCRIPTION
**Pull request by SmejoTT**
I created a basic model of a robot with 4 wheels. The robot can steer the front wheels and has 2 front white LEDs and 2 rear red LEDs. I used the Ackerman robot from [here](https://github.com/cyberbotics/webots/blob/released/projects/samples/howto/worlds/four_wheels.wbt). Then I used LEDs from [here](https://github.com/cyberbotics/webots/blob/released/projects/samples/devices/worlds/led.wbt). I also created an empty robot controller.

### CODE REVIEW

**Comment by Siliconlad** [comment]
@SmejoTT I updated some things to comply with CI (which doesn't run in this repo. that can be changed if you guys want).

**Comment by Siliconlad** [comment]
@SmejoTT could this be merged?

**Review by Siliconlad — CHANGES_REQUESTED** [review]
@SmejoTT I removed the dependency to `custom_msgs` in `CMakeLists.txt` and `package.xml` as well as the link to the deleted robot controller in `CMakeLists.txt`. I also set the controller for the robot to `<extern>`.

Before merging this, would it not be worth bringing the wheels closer to the robot now that we're not using steering?

**Comment by SmejoTT** [comment]
Yeah, that is a good idea, I will position the wheels to be closer.

**Review by Siliconlad — APPROVED** [review]
Looks good! Thanks @SmejoTT :)

**Pull request merged**
